server:
  address: 0.0.0.0
  port: 8080
appconfig:
  application: MyContainerApplication
  environment: MyContainerApplicationProductionEnvironment
  config: MyContainerApplicationConfigurationProfile
  cacheTtlInSeconds: 30